import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { SiteHeader } from "@/components/site-header";

export const dynamic = "force-dynamic";

const typeLabels = { PKL: "PKL", MAGANG: "Magang", FULL_TIME: "Full-Time" } as const;

export default async function CareerIndustriesPage({ searchParams }: { searchParams: Promise<{ tipe?: string }> }) {
  const requestedType = (await searchParams).tipe;
  const tipe = requestedType === "PKL" || requestedType === "MAGANG" || requestedType === "FULL_TIME" ? requestedType : undefined;
  const [jobs, companies] = await Promise.all([
    prisma.lowongan.findMany({ where: { status: "PUBLISHED", tipe }, include: { perusahaan: true }, orderBy: { createdAt: "desc" } }),
    prisma.perusahaan.findMany({ select: { id: true, nama: true }, orderBy: { nama: "asc" } }),
  ]);

  return <div className="native-page"><SiteHeader /><main className="career-page"><section className="career-hero"><div className="native-shell career-hero__inner"><div><p className="native-eyebrow">BKK &middot; Career Industries</p><h1>Build your path.<br /><em>Meet your future.</em></h1><p>Jembatan antara talenta Moklet dan industri yang siap bertumbuh bersama generasi digital.</p><div className="career-hero__actions"><a className="native-button native-button--light" href="#list-industries">Lihat peluang <span aria-hidden="true">-&gt;</span></a><Link className="career-hero__text-link" href="/kontak">Hubungi BKK <span aria-hidden="true">-&gt;</span></Link></div></div><div className="career-hero__art" aria-hidden="true"><span>career</span><strong>industries</strong><i>01</i></div></div></section><section className="career-list-section" id="list-industries"><div className="native-shell"><div className="career-list-heading"><div><p className="native-eyebrow native-eyebrow--dark">List Industries</p><h2>Peluang untuk langkah berikutnya.</h2></div><p>Pilih jalur yang paling dekat dengan minat dan keahlianmu.</p></div><div className="career-toolbar"><div className="career-filters"><Link className={!tipe ? "is-active" : ""} href="/career-industries">Semua posisi</Link>{Object.entries(typeLabels).map(([value, label]) => <Link className={tipe === value ? "is-active" : ""} href={`/career-industries?tipe=${value}`} key={value}>{label}</Link>)}</div><span className="career-result-count">{jobs.length} posisi &middot; {companies.length} industri</span></div><div className="career-list-layout"><aside className="career-company-list"><p>Partner industri</p>{companies.map((company) => <a href={`#company-${company.id}`} key={company.id}><span>{company.nama.slice(0, 2).toUpperCase()}</span>{company.nama}</a>)}</aside><section className="career-job-grid">{jobs.map((job) => <article className="career-job-card" id={`company-${job.perusahaan.id}`} key={job.id}><div className="career-job-card__brand"><span>{job.perusahaan.nama.slice(0, 2).toUpperCase()}</span><div><p>{job.perusahaan.nama}</p><small>{job.lokasi}</small></div><span className={`career-badge career-badge--${job.tipe.toLowerCase()}`}>{typeLabels[job.tipe]}</span></div><h3><Link href={`/career-industries/${job.slug}`}>{job.judulPosisi}</Link></h3><p className="career-job-card__description">{job.deskripsi}</p><div className="career-tags">{job.syaratKeahlian.split(",").map((tag) => <span key={tag}>{tag.trim()}</span>)}</div><Link className="career-apply-link" href={`/career-industries/${job.slug}#lamar`}>Lamar Cepat <span aria-hidden="true">-&gt;</span></Link></article>)}</section></div>{jobs.length === 0 && <p className="career-empty">Belum ada posisi untuk filter ini.</p>}</div></section></main></div>;
}
